#include <stdio.h>
#include "cpu.h"
#include "isa.h"

static void
nop(cpu *c, addressing_mode am) {
	printf("\tNOP");
	if (am == IMPLIED) 
		cpu_tick_clock(c); /* Takes one cycle more */
	else
		isa_load_read(c, am); /* Only used in undocumented NOPs */
	printf("\n");
}

ADD_INSTRUCTION(0xea, NOP, IMPLIED, nop);

/* Undocumented modes */
ADD_INSTRUCTION(0x04, NOP, ZERO_PAGE, nop);
ADD_INSTRUCTION(0x44, NOP, ZERO_PAGE, nop);
ADD_INSTRUCTION(0x64, NOP, ZERO_PAGE, nop);
ADD_INSTRUCTION(0x0c, NOP, ABSOLUTE, nop);
ADD_INSTRUCTION(0x14, NOP, INDEXED_ZERO_PAGE_X, nop);
ADD_INSTRUCTION(0x34, NOP, INDEXED_ZERO_PAGE_X, nop);
ADD_INSTRUCTION(0x54, NOP, INDEXED_ZERO_PAGE_X, nop);
ADD_INSTRUCTION(0x74, NOP, INDEXED_ZERO_PAGE_X, nop);
ADD_INSTRUCTION(0xd4, NOP, INDEXED_ZERO_PAGE_X, nop);
ADD_INSTRUCTION(0xf4, NOP, INDEXED_ZERO_PAGE_X, nop);
ADD_INSTRUCTION(0x80, NOP, IMMEDIATE, nop);
ADD_INSTRUCTION(0x1c, NOP, INDEXED_ABSOLUTE_X, nop);
ADD_INSTRUCTION(0x3c, NOP, INDEXED_ABSOLUTE_X, nop);
ADD_INSTRUCTION(0x5c, NOP, INDEXED_ABSOLUTE_X, nop);
ADD_INSTRUCTION(0x7c, NOP, INDEXED_ABSOLUTE_X, nop);
ADD_INSTRUCTION(0xdc, NOP, INDEXED_ABSOLUTE_X, nop);
ADD_INSTRUCTION(0xfc, NOP, INDEXED_ABSOLUTE_X, nop);
ADD_INSTRUCTION(0x1a, NOP, IMPLIED, nop);
ADD_INSTRUCTION(0x3a, NOP, IMPLIED, nop);
ADD_INSTRUCTION(0x5a, NOP, IMPLIED, nop);
ADD_INSTRUCTION(0x7a, NOP, IMPLIED, nop);
ADD_INSTRUCTION(0xda, NOP, IMPLIED, nop);
ADD_INSTRUCTION(0xfa, NOP, IMPLIED, nop);
